### ISSUE TITLE
Invoking restarts instead of marking tasks as :errored?

### ISSUE THREAD

**Issue by epeld** [Shinmera/simple-tasks#1]
Hello,
New to lisp and CLOS so tell me if this doesn't make sense but I have some `restart-case`s INSIDE my task funcs that I would like to be able to invoke instead of just giving up on the tasks when they break.

I am guessing I would need to remove the `handler-bind` in this code:
```
(defmethod run-task :around ((task task))
  (when (task-ready-p task)
    (restart-case
        (handler-bind ((error (lambda (err)
                                (setf (status task) :errored)
                                (setf (error-environment task) (dissect:capture-environment err)))))
          (setf (status task) :running)
          (call-next-method)
          (setf (status task) :completed))
      (stop ()
        :report "Stop the task."
        (setf (status task) :stopped)))))
```
but would it still work? Pointers very much appreciated!

**Comment by Shinmera** [comment]
The innermost handler decides what happens with a condition first. So, in order to avoid the default behaviour, have your handler form in the primary `run-task` method of your task subclass and invoke the restart there.

As an example, subclassing the call-task:
```
(defclass my-task (call-task) ())

(defmethod run-task ((task my-task))
  (handler-bind ((error (lambda (err) (invoke-restart 'some-restart))))
    (call-next-method)))

(let ((runner (make-instance 'runner))
      (task (make-instance 'my-task :func (lambda ()
                                            (restart-case (error "Whoa!")
                                              (some-restart ()
                                                0))))))
  (start-runner runner)
  (schedule-task task runner)
  (values (return-values task) task))
```

**Comment by epeld** [comment]
Would this approach still work if I wanted to let the user choose the restart interactively in the debugger?

My use case is that I am building a GUI application (so using your trivial-main-thread) and I want to have the main GUI loop _always_ running while I incrementally add event handlers and modify their implementations. During this process, if any event handler breaks I would like to inspect the condition in the debugger and then have the option of invoking a restart like "move on", i.e ignore that specific event.

**Comment by Shinmera** [comment]
Just call `invoke-debugger` on the condition in your handler then.

**Comment by epeld** [comment]
Got it, thanks!
